name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g yarn
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn test
          yarn build
        env:
          CI: true
      - name: docker build
        env:
          CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        run: docker build -t $DOCKER_REGISTRY_URL/$CONTAINER_IMAGE_NAME:latest .
      - name: docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        env:
          CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        run: docker push $DOCKER_REGISTRY_URL/$CONTAINER_IMAGE_NAME:latest
